version: '3.8'
services:
  movies:
    image: msujith/paytmmovies:latest
    ports:
      - "81:80"
    volumes:
      - "movvol"
    deploy:
      replicas: 3

  train:
    image: msujith/paytmtrain:latest
    ports:
      - "82:80"
    volumes:
      - "travol"
    deploy:
      replicas: 3

  dth:
    image: msujith/paytmdth:latest
    ports:
      - "83:80"
    volumes:
      - "dthvol"
    deploy:
      replicas: 3

  recharge:
    image: msujith/paytmrecharge:latest
    ports:
      - "84:80"
    volumes:
      - "recvol"
    deploy:
      replicas: 3
